{% set name = "hpbandster" %}
{% set version = "0.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hpbandster-{{ version }}.tar.gz
  sha256: 49ffc32688155b509e62f3617b52ae15a96c9bff2c996a23df83f279106c5921

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - configspace
    - netifaces
    - numpy
    - pyro4
    - python >={{ python_min }}
    - scipy
    - serpent
    - statsmodels

test:
  imports:
    - hpbandster
    - hpbandster.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/automl/HpBandSter
  summary: HyPerBAND on STERoids, a distributed Hyperband implementation with lots of room for improvement
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
